In [9]:
import pymongo as mg
import pandas as pd

In [10]:
client = mg.MongoClient(host='mongodb://localhost:27017/') # mongodb에 접속.
client

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

In [11]:
database = client['db_medicals'] # database 접속
database

Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db_medicals')

In [12]:
collection = database['RecurrenceOfSurgery'] #collection 접속
collection

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'db_medicals'), 'RecurrenceOfSurgery')

In [13]:
cursor = collection.find({}) # collection 내의 자료 확인
data_list = list(cursor)

In [14]:
df_ROS = pd.DataFrame(data_list)
df_ROS.head(2)

,_id,Unnamed: 0,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,...,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
0,64d377f5db47ffb29e6cdbde,0,1PT,22.8,3,51.0,0.0,0,0,0,...,3,51.6,36.6,14.4,0,-1.01,2048.5,4,Down,0
1,64d377f5db47ffb29e6cdbdf,1,2PT,44.9,4,26.0,0.0,0,0,0,...,0,40.8,7.2,17.8,0,-1.14,1753.1,4,Up,0

In [15]:
df_ROS.columns

Index(['_id', 'Unnamed: 0', '환자ID', 'Large Lymphocyte',
       'Location of herniation', 'ODI', '가족력', '간질성폐질환', '고혈압여부', '과거수술횟수',
       '당뇨여부', '말초동맥질환여부', '빈혈여부', '성별', '스테로이드치료', '신부전여부', '신장', '심혈관질환',
       '암발병여부', '연령', '우울증여부', '입원기간', '입원일자', '종양진행여부', '직업', '체중', '퇴원일자',
       '헤모글로빈수치', '혈전합병증여부', '환자통증정도', '흡연여부', '통증기간(월)', '수술기법', '수술시간',
       '수술실패여부', '수술일자', '재발여부', '혈액형', '전방디스크높이(mm)', '후방디스크높이(mm)', '지방축적도',
       'Instability', 'MF + ES', 'Modic change', 'PI', 'PT', 'Seg Angle(raw)',
       'Vaccum disc', '골밀도', '디스크단면적', '디스크위치', '척추이동척도', '척추전방위증'],
      dtype='object')

In [16]:
df_ROS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1894 entries, 0 to 1893
Data columns (total 53 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     1894 non-null   object
 1   Unnamed: 0              1894 non-null   int64
 2   환자ID                    1894 non-null   object
 3   Large Lymphocyte        1894 non-null   float64
 4   Location of herniation  1894 non-null   int64
 5   ODI                     462 non-null    float64
 6   가족력                     1843 non-null   float64
 7   간질성폐질환                  1894 non-null   int64
 8   고혈압여부                   1894 non-null   int64
 9   과거수술횟수                  1894 non-null   int64
 10  당뇨여부                    1894 non-null   int64
 11  말초동맥질환여부                1894 non-null   int64
 12  빈혈여부                    1894 non-null   int64
 13  성별                      1894 non-null   int64
 14  스테로이드치료                 1894 non-null   int64
 15  신부전여부                   1894 non-null   int64
 16  신장                      1894 non-null   int64
 17  심혈관질환                   1894 non-null   int64
 18  암발병여부                   1894 non-null   int64
 19  연령                      1894 non-null   int64
 20  우울증여부                   1894 non-null   int64
 21  입원기간                    1894 non-null   int64
 22  입원일자                    1894 non-null   int64
 23  종양진행여부                  1894 non-null   int64
 24  직업                      1479 non-null   object
 25  체중                      1894 non-null   float64
 26  퇴원일자                    1894 non-null   int64
 27  헤모글로빈수치                 1893 non-null   float64
 28  혈전합병증여부                 1894 non-null   int64
 29  환자통증정도                  1894 non-null   int64
 30  흡연여부                    1894 non-null   int64
 31  통증기간(월)                 1890 non-null   float64
 32  수술기법                    1813 non-null   object
 33  수술시간                    1840 non-null   float64
 34  수술실패여부                  1894 non-null   int64
 35  수술일자                    1894 non-null   int64
 36  재발여부                    1894 non-null   int64
 37  혈액형                     1894 non-null   object
 38  전방디스크높이(mm)             1894 non-null   float64
 39  후방디스크높이(mm)             1894 non-null   float64
 40  지방축적도                   1891 non-null   float64
 41  Instability             1894 non-null   int64
 42  MF + ES                 1894 non-null   float64
 43  Modic change            1894 non-null   int64
 44  PI                      1890 non-null   float64
 45  PT                      1890 non-null   float64
 46  Seg Angle(raw)          1893 non-null   float64
 47  Vaccum disc             1894 non-null   int64
 48  골밀도                     998 non-null    float64
 49  디스크단면적                  1893 non-null   float64
 50  디스크위치                   1894 non-null   int64
 51  척추이동척도                  1894 non-null   object
 52  척추전방위증                  1894 non-null   int64
dtypes: float64(16), int64(31), object(6)
memory usage: 784.4+ KB

In [17]:
df_ROS_drops = df_ROS.drop(columns=['_id', 'Unnamed: 0'])
df_ROS_drops

,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,말초동맥질환여부,...,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
0,1PT,22.8,3,51.0,0.0,0,0,0,0,0,...,3,51.6,36.6,14.4,0,-1.01,2048.50,4,Down,0
1,2PT,44.9,4,26.0,0.0,0,0,0,0,0,...,0,40.8,7.2,17.8,0,-1.14,1753.10,4,Up,0
2,3PT,53.0,3,NaN,0.0,0,0,1,0,0,...,0,67.5,27.3,10.2,0,-1.77,1749.00,4,Down,0
3,4PT,54.7,4,18.0,0.0,0,1,0,0,0,...,0,49.2,18.7,19.9,0,-1.58,1796.20,4,Down,0
4,5PT,53.8,4,NaN,0.0,0,1,0,0,0,...,0,58.8,14.7,5.2,0,-0.79,2021.48,4,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1889,1890PT,44.0,1,NaN,0.0,0,0,0,0,0,...,2,59.5,23.0,21.8,0,NaN,2652.20,5,Middle,0
1890,1891PT,30.8,2,NaN,0.0,0,0,0,0,0,...,0,47.7,20.2,5.0,0,NaN,1795.80,4,Down,0
1891,1892PT,36.7,3,NaN,0.0,0,0,0,0,1,...,0,44.6,15.0,17.4,1,NaN,2624.40,4,Down,0
1892,1893PT,32.5,2,NaN,0.0,0,0,0,0,0,...,2,32.2,11.1,17.7,0,NaN,1972.50,5,Down,0
1893,1894PT,49.5,2,NaN,0.0,0,0,0,0,0,...,0,38.9,6.8,27.8,0,NaN,1574.40,5,Middle,0

In [18]:
df_ROS_drops.describe()

,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,말초동맥질환여부,빈혈여부,...,MF + ES,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추전방위증
count,1894.000000,1894.000000,462.000000,1843.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,1894.000000,...,1894.000000,1894.000000,1890.000000,1890.000000,1893.000000,1894.000000,998.000000,1893.000000,1894.000000,1894.000000
mean,39.270750,2.295671,31.142857,0.049919,0.020063,0.130940,0.302534,0.062830,0.004224,0.024287,...,2096.421600,0.247096,46.593651,16.329841,15.287934,0.056494,-1.507325,1989.788774,4.430834,0.032207
std,13.675874,0.996143,10.131304,0.217836,0.140254,0.337424,0.638461,0.242721,0.064871,0.153980,...,472.834488,0.661506,22.736211,8.421322,10.426397,0.230935,0.495867,314.478436,3.595680,0.176596
min,0.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1016.800000,0.000000,11.900000,-10.600000,-27.400000,0.000000,-2.840000,1145.800000,1.000000,0.000000
25%,30.700000,1.000000,24.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1765.285000,0.000000,38.700000,10.500000,8.800000,0.000000,-1.820000,1777.000000,4.000000,0.000000
50%,40.200000,2.000000,31.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2056.500000,0.000000,45.100000,15.700000,14.500000,0.000000,-1.520000,1985.500000,4.000000,0.000000
75%,48.600000,3.000000,38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2374.350000,0.000000,52.000000,21.400000,21.100000,0.000000,-1.202500,2178.500000,4.000000,0.000000
max,89.000000,5.000000,68.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,...,5569.000000,3.000000,559.000000,48.700000,165.000000,1.000000,1.700000,3214.200000,45.000000,1.000000

In [14]:
df_ROS_drops.describe(include=object)

        환자ID    직업  수술기법   혈액형  척추이동척도
count   1894  1479  1813  1894    1894
unique  1894    17     2     4       5
top      1PT   사무직  TELD  RH+A  Middle
freq       1   449  1673   688    1260

In [19]:
df_ROS_drops['직업'].value_counts()

사무직      449
자영업      171
무직       164
학생       135
주부       114
군인        90
공무원       51
운수업       50
노동직       42
농업        40
의료직       40
사업가       39
교사        30
특수전문직     23
건설업       17
운동선수      14
예술가       10
Name: 직업, dtype: int64

In [20]:
df_ROS_drops['혈액형'].value_counts()

RH+A     688
RH+O     532
RH+B     476
RH+AB    198
Name: 혈액형, dtype: int64

In [24]:
df_ROS_drops[['재발여부','척추이동척도']].value_counts()

재발여부  척추이동척도
0     Middle            1110
      Down               454
1     Middle             150
      Down                59
0     Up                  53
      Extremely down      34
      Extremely up        16
1     Up                  12
      Extremely down       6
dtype: int64

In [25]:
df_ROS_drops[['척추이동척도']].value_counts()

척추이동척도
Middle            1260
Down               513
Up                  65
Extremely down      40
Extremely up        16
dtype: int64

In [26]:
df_ROS_drops[['디스크위치']].value_counts()

디스크위치
4        1458
5         271
3         112
2          27
45          9
34          8
10          2
11          2
1           1
12          1
23          1
25          1
35          1
dtype: int64

In [27]:
df_ROS_drops[['가족력']].value_counts()

가족력
0.0    1751
1.0      92
dtype: int64

In [28]:
df_ROS_drops[['재발여부']].value_counts()

재발여부
0       1667
1        227
dtype: int64

In [29]:
df_ROS_drops[['재발여부','수술시간']].value_counts()

재발여부  수술시간
0     45.0     112
      60.0     108
      40.0      88
      35.0      85
      30.0      81
              ...
      165.0      1
      155.0      1
      152.0      1
      151.0      1
1     145.0      1
Length: 203, dtype: int64

In [30]:
df_ROS_drops[['수술시간']].value_counts()

수술시간
45.0     124
60.0     119
40.0     102
35.0      94
30.0      89
        ...
13.0       1
12.0       1
10.0       1
7.0        1
220.0      1
Length: 134, dtype: int64